### PR TITLE
Add new fields for retrieving owners by lastName.

### PR DESCRIPTION
**Pull request by champagne**
Add a new method for retrieving owners by the lastName. Got test result as following.

image

### CODE REVIEW

**Comment by nilshartmann** [comment]
Hi,

thank you very much for your pull request.

Would you mind making the field a little more "general"?

like "ownersByCriteria(criteria: { lastName: "..." })

I think that would be more "GraphQL-ish", as it allows more flexibility for clients.

**Comment by champagne** [comment]
Sure, will do it soon.

**Comment by champagne** [comment]
Hi Nils,

For your comment, one question, should we consider the **and/or** logic between multiple fields in the criteria?

BR,
Sam

**Comment by nilshartmann** [comment]
Hi Sam,

I think 'and' semantic would be the way to go. 

What do you think?

**Comment by champagne** [comment]
Hi Nils,

Please have a look at my code branch.
image
image


BR,
Sam

**Comment by nilshartmann** [comment]
Hi Sam,

thank you very much for your contribution!

**Comment by champagne** [comment]
Hi Nils,

I'm so glad could be a contributor of spring-petclinic-graphql.
I will try to do more later.

BR,
Sam.

**Pull request merged**
